name: ZixuanZ

github:
  url: http://localhost:4000
  
# Dependencies
markdown:    kramdown
highlighter: pygments

# Blog Setup
permalink: /blog/:year/:month/:day/:title

gems: [jekyll-paginate]

paginate: 5
