# Site Settings
#url: "https://zixuanz.github.io"
#baseurl:

#github:
#  url: http://localhost:4000

# Dependencies
markdown:    kramdown
highlighter: pygments

# Blog Settings
permalink: /blog/:year/:month/:day/:title

gems: [jekyll-paginate]

paginate: 5
